
name: petnest
description: "A high-fidelity frontend prototype for the PetNest app, built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  animations: ^2.0.11
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
    android: true
    ios: true
    image_path: "assets/icons/logopng.png"


flutter:
  uses-material-design: true


  assets:
    - assets/icons/
    - assets/icons/logopng.png

